function usdaily = importfile1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  USDAILY = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  USDAILY = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  usdaily = importfile("/Users/isaac_weintraub_admin/Projects/COVID19/covid-tracking-data/data/us_daily.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jul-2020 12:05:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["date", "states", "positive", "negative", "pending", "hospitalizedCurrently", "hospitalizedCumulative", "inIcuCurrently", "inIcuCumulative", "onVentilatorCurrently", "onVentilatorCumulative", "recovered", "dateChecked", "death", "hospitalized", "lastModified", "total", "totalTestResults", "posNeg", "deathIncrease", "hospitalizedIncrease", "negativeIncrease", "positiveIncrease", "totalTestResultsIncrease", "hash"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["dateChecked", "lastModified", "hash"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["dateChecked", "lastModified", "hash"], "EmptyFieldRule", "auto");

% Import the data
usdaily = readtable(filename, opts);

end